#!/bin/bash
set -e -x

cd $(dirname $0)/..

. ./scripts/version.sh

TAG=${TAG:-${VERSION_TAG}${SUFFIX}}
REPO=${REPO:-rancher}
IMAGE_NAME=${IMAGE_NAME:-k3s-assets}
IMAGE=${REPO}/${IMAGE_NAME}:${TAG}

gh release download "${VERSION}" --dir ./dist/artifacts

oras push "${IMAGE}" ./dist/artifacts
